/**
 * Landing v2 "Prism" — diccionario de traducción.
 *
 * El español es el idioma por defecto: cada componente pasa su copy ES literal
 * inline a `t(key, esDefault)` del provider. Este módulo sólo contiene el
 * diccionario EN (portado verbatim del `en()` del diseño `LandingPrism v2.dc.html`,
 * líneas 1198-1281). Cuando `lang === 'en'`, `t` devuelve `EN_DICT[key]`
 * (fallback al ES por defecto si la key no existe).
 *
 * Algunas entradas de módulos (`mp*_s*`) contienen HTML (`<strong>…</strong>`) —
 * los componentes que las usan (ModulosPro) las renderizan con
 * `dangerouslySetInnerHTML`; las demás son texto plano.
 */
export const EN_DICT: Record<string, string> = {
  nav_marca: 'Your brand',
  nav_producto: 'Product',
  nav_precios: 'Pricing',
  nav_login: 'Sign in',
  nav_cta: 'Create account',
  nav_modulos: 'Modules',
  ft_modulos: 'Modules',

  hero_1: 'One platform.',
  hero_grad: 'Your brand.',
  hero_sub:
    'Training, nutrition and an installable app with your logo and your color — your whole Personal Training business in one panel. You coach your clients; EVA handles the rest.',
  hero_cta1: 'Create my free account →',
  hero_cta2: 'See how it looks →',
  brand_rail: '// the color is yours',
  brand_auto: '↻ auto',

  s_wl_mark: '// white-label',
  s_wl_title: 'Same engine. A thousand different brands.',
  s_wl_lede:
    'Your client never sees “EVA”. They see your logo, your name and your color on their phone’s home screen. Tap a color above to lock it — the whole site changes with you.',
  wl_p1t: 'Your color, on every screen',
  wl_p1d: 'Pick a brand color and EVA applies it to buttons, rings, glows and accents across the client app.',
  wl_p2t: 'Your logo and your name',
  wl_p2d: 'Upload your logo and the app installs with your brand. EVA stays behind the scenes, always.',
  wl_p3t: 'Simple access for your client',
  wl_p3d: 'Your client logs in with a 5-digit code — no app stores, no downloads, no friction.',
  wl_try: '// try it live · lock a color',
  wl_auto: '↻ auto',

  m_mark: '// 02 · professional modules',
  m_title: 'The tools real professionals use.',
  m_lede:
    'Each module replaces a tool you do by hand today —in Excel, Canva or a calculator— and turns it into something automatic, with your brand and with history. The coach measures and prescribes; the client just sees their result.',
  m_addon: 'add-on · $9,990/mo each · switch on only what you use',
  m_t1: 'Cardio by zones',
  m_l1: 'Cardiovascular prescription',
  m_t2: 'Movement screening',
  m_l2: '7-pattern assessment',
  m_t3: 'Body composition',
  m_l3: 'ISAK anthropometry + BIA',
  m_t4: 'Exchange-based nutrition',
  m_l4: 'The Chilean method, digital',

  s1_mark: '// 01 · coach panel',
  s1_title: 'Your whole business, in one panel.',
  s1_lede:
    'Leave the spreadsheets and PDFs behind. Every module is built to run 30+ clients without losing control.',
  f1_t: 'Routine builder',
  f1_d: 'Supersets, RIR, rest timers and {{count}} exercises with GIFs. Build once, assign to as many clients as you want.',
  f2_t: 'Nutrition',
  f2_d: 'Meal plans with computed macros and daily client logging from their app. Available from the Pro plan.',
  f3_t: 'Live tracking',
  f3_d: 'Adherence, PRs, weight and streaks for every client, in real time. Automatic alerts when someone falls behind.',
  f4_t: 'Your brand, not ours',
  f4_d: 'Your logo, your color and your name on the app your client installs. EVA stays behind the scenes.',
  f1_tag: '{{count}} exercises',
  f2_tag: 'macros · daily log',
  f3_tag: 'real time',
  f4_tag: 'white-label',
  stat1: 'exercises with gifs',
  stat2: 'muscle groups',
  stat3: 'your brand visible',
  stat4: 'plan to start',

  s3_mark: '// 02 · pricing',
  s3_title: 'Pay per client slot.',
  s3_lede: 'No contracts. Change or cancel anytime. Save up to 20% with annual prepay.',
  cyc_m: 'Monthly',
  cyc_q: 'Quarterly −10%',
  cyc_a: 'Annual −20%',
  cyc_note: '// monthly equivalent · billed per period · clp',
  pf_sub: 'Try EVA without a card. Up to 3 clients, forever.',
  p_unit: 'clp / mo',
  p_unit2: 'clp / mo',
  p_unit3: 'clp / mo',
  pf_1: 'Up to 3 active clients',
  pf_2: 'Full routine builder',
  pf_3: '{{count}}-exercise GIF catalog',
  pf_4: 'No nutrition module',
  pf_cta: 'Start free',
  badge_pop: 'most popular',
  pp_sub: 'The usual sweet spot: more slots and nutrition included.',
  pp_1: '11–30 active clients',
  pp_2: 'Nutrition plans included',
  pp_3: 'White-label: your logo and color',
  pp_4: 'Check-ins, progress and alerts',
  pp_cta: 'Choose Pro →',
  pe_sub: 'For established businesses with high client volume.',
  pe_1: '31–60 active clients',
  pe_2: 'Everything in Pro, more slots',
  pe_3: 'Annual prepay discounts',
  pe_4: 'Priority support',
  pe_cta: 'Choose Elite',
  table_note:
    '// also: starter (1–10) · growth (61–120) · scale (up to 500) — all with unlimited routines and dashboard',

  tm_mark: '// teams mode',
  tm_title: 'More than one coach? Work in the same panel.',
  tm_lede:
    'Teams mode: a shared client pool, per-coach data isolation and team reports in one place. For duos, studios and boutique gyms.',
  tm_cta: 'Learn about Teams →',
  tm_p1t: 'Shared client pool',
  tm_p1d: 'Assign clients to coaches in one click.',
  tm_p2t: 'Per-coach data isolation',
  tm_p2d: 'Privacy enforced at the database level.',
  tm_p3t: 'Team reports',
  tm_p3d: 'Everyone’s adherence and alerts, live.',

  fin_mark: '// ready when you are',
  fin_title: 'Take your coaching pro.',
  fin_sub: 'Create your account in minutes and adjust your plan as you grow. Start free, no card.',
  fin_cta1: 'Create my account →',
  fin_cta2: 'Write to us',

  ft_marca: 'Your brand',
  ft_producto: 'Product',
  ft_precios: 'Pricing',
  ft_legal: 'Legal',
  ft_mono: '// made in chile · installable pwa · no third-party tracking',

  mcta_cta: 'Create my account →',
  mcta_cta2: 'Create my account →',
  mcta_login: 'Sign in',

  ts_mark: '// coaches already running on eva',
  ts_title: 'Less spreadsheet. More coaching.',
  t1_q: '“I went from five spreadsheets to an app with my logo in one afternoon. My clients log on their own; I just review the alerts.”',
  t1_r: 'online coach · 28 clients',
  t2_q: '“The builder saves me hours every week: I build the base routine once and tune it per client in minutes.”',
  t2_r: 'strength coach · 41 clients',
  t3_q: '“My clients think the app is mine. For my brand, that alone pays for the plan.”',
  t3_r: 'boutique studio · 2 coaches',

  faq_mark: '// frequently asked questions',
  faq_title: 'Before you ask.',
  q1: 'Can I cancel anytime?',
  a1: 'Yes. No contracts: change plans or cancel from your panel and keep access until the end of the paid period.',
  q2: 'What if I outgrow my client slots?',
  a2: 'Upgrade to the next plan in one click. Nothing is deleted: routines, history and clients stay intact.',
  q3: 'Do my clients pay anything for the app?',
  a3: 'No. They install your app for free and log in with a 5-digit code. You only pay your coach plan.',
  q4: 'Can I migrate my routines from Excel?',
  a4: 'Yes. Load a routine once in the builder —with the {{count}}-exercise catalog— and reuse it with as many clients as you want.',
  q5: 'Do I need a card to start?',
  a5: 'No. The Free plan is permanent for up to 3 clients, no card, with the full builder.',

  mp0_t: 'Cardio by heart-rate zones',
  mp0_d: 'Turns “do 30 minutes of jogging” into a real prescription: effort zones computed for each client’s body, not a generic table.',
  mp0_s1: 'Enter the client’s age and pulse once; EVA computes their <strong style="color:#fff;">5 personalized zones</strong>.',
  mp0_s2: 'Prescribe by zone, pace (min/km) and intervals: “8×400 m in Z4, 90 s rest”.',
  mp0_s3: 'The client sees <strong style="color:#fff;">“Z4 · 150–168 bpm”</strong> with a guiding timer, and logs what they did.',
  mp1_t: 'Movement screening',
  mp1_d: 'Spot where your client moves poorly and where injury risk hides —before they get hurt. What a physio does in an initial assessment.',
  mp1_s1: 'Score <strong style="color:#fff;">7 key patterns</strong> from 0–3; left and right separately.',
  mp1_s2: 'EVA returns an automatic <strong style="color:#fff;">priority traffic light</strong>: red, yellow or green.',
  mp1_s3: 'Every screening is saved: track evolution with line and radar charts.',
  mp2_t: 'Body composition',
  mp2_d: 'Measure what the body is made of —fat, muscle, bone— with professional rigor, not just “step on the scale”. Supports both industry methods.',
  mp2_s1: '<strong style="color:#fff;">Bioimpedance</strong> (InBody, Tanita, Omron) or manual <strong style="color:#fff;">ISAK anthropometry</strong>.',
  mp2_s2: '8 skinfolds, 8 girths and 6 diameters → EVA computes everything, no Excel errors.',
  mp2_s3: 'Body split into <strong style="color:#fff;">5 components</strong> + somatotype + fat %, with before/after history.',
  mp3_t: 'Exchange-based nutrition',
  mp3_d: 'Digitizes the portion method taught in Chilean universities. Clients swap equivalent foods on their own, without weighing everything in grams.',
  mp3_s1: 'Assign portions per meal with <strong style="color:#fff;">9 Chilean exchange groups</strong>.',
  mp3_s2: 'EVA computes calories and macros on its own, and builds day variants without redoing the plan.',
  mp3_s3: 'Generates the plan as a <strong style="color:#fff;">PDF with your brand</strong> —your logo and color, not EVA’s.',
}
